devices:
  - type: RingV2
    name: RingV2
    address: D029833A-E1B7-5520-F242-D08B78F90D4D

nodes:
  - type: GestureDetector
    name: GestureDetector
    input_edges:
      imu: RingV2_imu
      touch: RingV2_touch
    output_edges:
      gesture: gesture
    num_classes: 44
    imu_window_length: 200
    gesture_window_length: 3
    checkpoint_file: checkpoint/gesture_hz.pt
    execute_interval: 8
    confidence_threshold: 0.9
    labels: [ none, wave_right, wave_down, wave_left, wave_up, tap_air, tap_plane, push_forward,
              pinch, clench, flip, wrist_clockwise, wrist_counterclockwise, circle_clockwise,
              circle_counterclockwise, clap, snap, thumb_up, middle_pinch, index_flick, touch_plane,
              thumb_tap_index, index_bend_and_straighten, ring_pinch, pinky_pinch, slide_plane,
              pinch_down, pinch_up, boom, tap_up, throw, touch_left, touch_right, slide_up,
              slide_down, slide_left, slide_right, aid_slide_left, aid_slide_right, touch_up,
              touch_down, touch_ring, long_touch_ring, spread_ring]
