devices:
  - type: RingV2
    name: RingV2
    address: B8F94FEA-2353-018E-F079-D8F47C152048
    input_edges:
      action: Receiver_ACTION
detectors:
  - type: Receiver
    name: Receiver
    input_edges:
      imu: RingV2_IMU
      mic: RingV2_mic
      touch: RingV2_TOUCH
      touch_raw: RingV2_TOUCH_RAW
      battery: RingV2_BATTERY
      ppg_r: RingV2_PPG_R
      ppg_g: RingV2_PPG_G
      ppg_hr: RingV2_PPG_HR
      ppg_spo2: RingV2_PPG_SPO2
    output_edges:
      action: ACTION
  - type: ImuVisualizer
    name: ImuVisualizer
    input_edges:
      imu: RingV2_IMU
    output_edges: {}
