devices:
  - type: RingV2
    name: RingV2
    drift: [0.44, 0.23, -0.03]
    address: B8F94FEA-2353-018E-F079-D8F47C152048

nodes:
  - type: GestureDetector
    name: GestureDetector
    input_edges:
      imu: RingV2_IMU
      touch: RingV2_TOUCH
      battery: RingV2_BATTERY
    output_edges:
      gesture: gesture
    num_classes: 4
    imu_window_length: 20
    gesture_window_length: 3
    checkpoint_file: checkpoint/touch_event.pth
    execute_interval: 1
    confidence_threshold: 0.8
    labels: [ ALWAYS_CONTACT, ALWAYS_NO_CONTACT, UP, DOWN ]