devices:
  - type: Ring
    name: Ring
    address: 609CD89E-6220-4A33-C175-CE350F498AB9
    # address: 0D85597D-C82C-E839-E0E0-4776246A6398

nodes:
  - type: GestureDetector
    name: GestureDetector
    input_edges:
      imu: Ring_imu
      touch: Ring_touch
      battery: Ring_battery
    output_edges:
      gesture: gesture
    num_classes: 4
    imu_window_length: 20
    gesture_window_length: 3
    checkpoint_file: checkpoint/touch_event.pth
    execute_interval: 1
    confidence_threshold: 0.8
    labels: [ ALWAYS_CONTACT, ALWAYS_NO_CONTACT, UP, DOWN ]
