all_people:
- jjx
- lsq
- hsq
- qp
- mfj
- cm
- fhy
- zsn
- gx
- qk
- hm
- lxt
- gsq
- jc
- hfx
- ylc
- lzj
- cyf
- wxy
- zqy
dataset_path: ../../../local/dataset/0_ring_gesture_dataset
raw_data_path: ../../../local/dataset/0_ring_gesture_dataset_raw
test_people:
- jjx
- lsq
- hsq
- qp
train_people:
- mfj
- cm
- fhy
- zsn
- gx
- qk
- hm
- lxt
- gsq
- jc
- hfx
- ylc
- lzj
- cyf
- wxy
- zqy
