all_people:
- wxy
- jjx
- hm
- hfx
- qp
- qk
- cm
- mfj
- zqy
- gsq
- lzj
- cyf
- lsq
- fhy
- hsq
- lxt
- ylc
- jc
- gx
- zsn
dataset_path: ../../../local/dataset/0_ring_gesture_dataset
raw_data_path: ../../../local/dataset/0_ring_gesture_dataset_raw
test_people:
- wxy
- jjx
- hm
- hfx
train_people:
- qp
- qk
- cm
- mfj
- zqy
- gsq
- lzj
- cyf
- lsq
- fhy
- hsq
- lxt
- ylc
- jc
- gx
- zsn
