devices:
  - type: Tello
    name: Tello
    # ip: 192.168.3.15
    ip: 192.168.100.167
    ar_video_ip: 192.168.3.18
    input_edges:
      action: DroneController_command

  - type: GshxAR
    name: GshxAR
    input_edges:
      objects: Commander_objects
    ip: 192.168.3.18

  - type: Ring
    name: Ring
    address: 609CD89E-6220-4A33-C175-CE350F498AB9

nodes:
  - type: DroneController
    name: DroneController
    input_edges:
      imu: Ring_imu
      touch: Ring_touch
    output_edges:
      command: command

  - type: ObjectDetector
    name: ObjectDetector
    input_edges:
      video: Tello_video
    output_edges:
      objects: objects

  - type: Commander
    name: Commander
    input_edges:
      eye: GshxAR_eye
      objects: ObjectDetector_objects
    output_edges:
      objects: objects

  - type: FrameVisualizer
    name: FrameVisualizer
    input_edges:
      video: Tello_video
      objects: ObjectDetector_objects
    output_edges: {}